name = "camp-sites-map-new"
compatibility_date = "2024-02-23"
main = "./.svelte-kit/cloudflare/_worker.js"

[site]
bucket = ".svelte-kit/cloudflare"

[build]
command = "npm run build"

[site.static]
include = [
  "**/*.html",
  "**/*.css",
  "**/*.js",
  "**/*.json",
  "**/*.ico",
  "**/*.png",
  "**/*.jpg",
  "**/*.svg"
]
