compatibility_date = "2024-02-23"
name = "camp-sites-map-new"
workers_dev = true
main = "./.svelte-kit/cloudflare/_worker.js"

[vars]
# Add your environment variables here if needed

[build]
command = "npm run build"

[site]
bucket = ".svelte-kit/cloudflare"
